guestList = ['Lebron James', 'Martin Luther King Jr', 'Bill Gates']
print(f"Dear {guestList[0].title()}, I would like to invite you to dinner.")
print(f"Dear {guestList[1].title()}, I would like to invite you to dinner.")
print(f"Dear {guestList[2].title()}, I would like to invite you to dinner.")
print(f"\nI am sorry, {guestList[1].title()} can't make it to dinner.")
guestList[1] = 'Steve Jobs'
print(f"Dear {guestList[0].title()}, I would like to invite you to dinner.")
print(f"Dear {guestList[1].title()}, I would like to invite you to dinner.")
print(f"Dear {guestList[2].title()}, I would like to invite you to dinner.")
print('\nI found a bigger table!')
guestList.insert(0, 'Mark Zuckerberg')
guestList.insert(2, 'Elon Musk')
guestList.append('Jeff Bezos')
print(f"Dear {guestList[0].title()}, I would like to invite you to dinner.")
print(f"Dear {guestList[1].title()}, I would like to invite you to dinner.")
print(f"Dear {guestList[2].title()}, I would like to invite you to dinner.")
print(f"Dear {guestList[3].title()}, I would like to invite you to dinner.")
print(f"Dear {guestList[4].title()}, I would like to invite you to dinner.")
print(f"Dear {guestList[5].title()}, I would like to invite you to dinner.")

print('\n I can only invite two people to dinner unfortunatly my dinner table wont arrive in time.')
uninvited = guestList.pop()
print(guestList)
print(f"\nSorry {uninvited.title()}, I can't invite you to dinner.")
guestList.pop()
uninvited = guestList.pop()
print(f"\nSorry {uninvited.title()}, I can't invite you to dinner.")
guestList.pop()
uninvited = guestList.pop()
print(f"\nSorry {uninvited.title()}, I can't invite you to dinner.")
guestList.pop()
print(guestList)
